---
image:
  # overwritten via --set argument
  repository: djangofluent/django-fluent.org
  pullSecrets:
  - name: gitlab-registry
envSecret: "djangofluent-env-prd"
env:
  ALLOWED_HOSTS: "django-fluent.org"
  CSRF_COOKIE_SECURE: "true"
  SESSION_COOKIE_SECURE: "true"
persistence:
  enabled: true
readinessProbe:
  enabled: false
livenessProbe:
  periodSeconds: 300
nodeSelector:
  # Stay on the same host for GKE storage
  purpose: apps
ingress:
  enabled: true
  hosts:
  - django-fluent.org
  annotations:
    #incompatible with certmanager: ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: 'letsencrypt-prod'
    certmanager.k8s.io/acme-challenge-type: http01
    nginx.ingress.kubernetes.io/server-alias: "django-fluent.com djangofluent.org djangofluent.com www.django-fluent.org www.django-fluent.com www.djangofluent.org www.djangofluent.com"
  tls:
  - secretName: djangofluent-tls-prd
    hosts:
    - django-fluent.org
    - www.django-fluent.org
