---
image:
  # overwritten via --set argument
  repository: djangofluent/django-fluent.org
  pullSecrets:
  - name: gitlab-registry
envSecret: "djangofluent-prd-env"
env:
  ALLOWED_HOSTS: "django-fluent.org"
  CSRF_COOKIE_SECURE: "true"
  SESSION_COOKIE_SECURE: "true"
securityContext:
  runAsUser: 1001  # django-fluent.org on experience
  fsGroup: 1001  # wsgiusers on experience
persistence:
  enabled: true
readinessProbe:
  enabled: false
livenessProbe:
  periodSeconds: 300
ingress:
  enabled: true
  hosts:
  - django-fluent.org
  annotations:
    ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: 'letsencrypt-prod'
    certmanager.k8s.io/acme-challenge-type: http01
  tls:
  - secretName: djangofluent-prd-tls
    hosts:
    - django-fluent.org
