apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: djangofluent
  environment: tst
  release: djangofluent-tst

configMapGenerator:
  - literals:
      - ALLOWED_HOSTS=django-fluent.test.edoburu.nl
      - CSRF_COOKIE_SECURE=true
      - ROBOTS_TXT_DISALLOW_ALL=true
      - SENTRY_ENVIRONMENT=test
      - SESSION_COOKIE_SECURE=true
    name: djangofluent-env

namespace: fluentdemo
nameSuffix: -tst

patchesStrategicMerge:
  - patches.yml

resources:
  - ../../base
  - ingress.yml
